# config.yaml

max_results: 50 # max number of results shown
past_days: 30 # number of days to check from today
# past_days: 36525 # to search all the arxiv (for old papers or when arxiv_sortorder is ascending)
literal: true # literal search of keywords
run_scirate: false # fetch scirates?

# sorting entries in arxiv API
# how the entries are sorted BEFORE fetching them:
# descending -> FETCH new papers first
# ascending -> FETCH old papers first (also see past_days for old papers)
arxiv_sortby: "submittedDate" # "relevance", "lastUpdatedDate"
arxiv_sortorder: "descending" # "ascending"

# sorting entries in speed-the-arxiv
# how the entries are sorted (and shown) AFTER fetching them:
# descending -> SHOW new papers first
# ascending -> SHOW old papers first
sortby: ['date', 'scirate'] # possible options: title, date, scirate, category
sortorder_rev: true # true: descending order, false: ascending order

# andor vars decide how to search for keyauthors and keywords
# they can take the value "+OR+", "+AND+", "+ANDNOT+"
# "+OR+" -> select all the results with ANY of the keys
# "+AND+" -> select all the results with ALL the keys
# "+ANDNOT+" -> select all the result with none of the keys
and_or_sections: "+OR+"
and_or_keyauthors: "+OR+"
and_or: "+OR+"
and_or_keywords: "+OR+"

keys:
    # if you do not want to specify some keys, leave the list empty []
    sections: [quant-ph]
    keyauthors: [prosen, babbush, cirac]
    keywords: [nisq, adiabatic]

# additional keys: vqa, encoding
